# Generated by Django 2.2.6 on 2019-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_link', models.CharField(max_length=2000)),
                ('short_link', models.CharField(max_length=1000)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
